# Generated by Django 4.0.3 on 2022-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unitMeasure', models.CharField(max_length=100)),
                ('purchased', models.BooleanField(default=False)),
                ('imageURL', models.CharField(max_length=200)),
            ],
        ),
    ]
